"use client";
import { useState } from "react";
import type { Video } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from "@/components/ui/empty";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
const categories = ["Business-Ideen / Sidehustles", "Sportwetten", "KDP-Buchbusiness", "KI & Automation"];
export default function Dashboard({ videos, queue }: { videos: Video[]; queue: { videoId: string; reason: string }[] }) {
 const [query, setQuery] = useState(""); const [category, setCategory] = useState("Alle Bereiche"); const [status, setStatus] = useState("Alle Prüfstände");
 const filtered = videos.filter(v => (category === "Alle Bereiche" || v.categories.includes(category)) && (status === "Alle Prüfstände" || (status === "Noch ungeprüft" ? !v.revisions.length : status === "Erneut prüfen" ? queue.some(q => q.videoId === v.id) : !!v.revisions.length)) && [v.title, v.summary, v.channel, ...v.tags].join(" ").toLocaleLowerCase("de").includes(query.toLocaleLowerCase("de")));
 return <main className="workspace"><header className="masthead"><a href="/" className="brand">MC<span>WISSENSPLATTFORM</span></a><form action="/api/logout" method="post"><Button variant="outline" type="submit">Abmelden</Button></form></header>
 <section className="heading"><div><p className="eyebrow">DEIN RECHERCHEARCHIV</p><h1>Wissen, das einer<br className="desktop-break"/> Prüfung standhält.</h1></div><p className="heading-note">Ideen entdecken. Belege hinterfragen.<br/>Erkenntnisse mit jedem Video weiterentwickeln.</p></section>
 <section className="metrics" aria-label="Übersicht"><div><strong>{videos.length}</strong><span>Analysen</span></div><div><strong>{videos.filter(v => v.revisions.length).length}</strong><span>Mit Gegenprüfung</span></div><div><strong>{queue.length}</strong><span>Erneut zu prüfen</span></div></section>
 <section className="library"><div className="section-heading"><h2>Deine Bibliothek</h2><a href="/methodik">So bewerten wir</a></div>
 <div className="controls"><label className="search"><span className="sr-only">Analysen durchsuchen</span><Input placeholder="Titel, Thema oder Tool suchen …" value={query} onChange={e => setQuery(e.target.value)}/></label><Select value={category} onValueChange={setCategory}><SelectTrigger aria-label="Themenbereich"><SelectValue/></SelectTrigger><SelectContent>{["Alle Bereiche", ...categories].map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger aria-label="Prüfstand"><SelectValue/></SelectTrigger><SelectContent>{["Alle Prüfstände", "Noch ungeprüft", "Mit Gegenprüfung", "Erneut prüfen"].map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div>
 <p className="small muted" role="status">{filtered.length} {filtered.length === 1 ? "Analyse" : "Analysen"}</p>
 {!filtered.length ? <Empty className="empty-state"><EmptyHeader><EmptyTitle>{videos.length ? "Keine passenden Analysen" : "Platz für deine erste Analyse"}</EmptyTitle><EmptyDescription>{videos.length ? "Ändere den Suchbegriff oder die Filter." : "Lade deine erste HTML-Datei im gemeinsamen Codex-Task hoch. Nach dem Import findest du hier die Analyse, ihre Einordnung und unsere Gegenprüfung."}</EmptyDescription></EmptyHeader>{videos.length > 0 && <Button variant="outline" onClick={() => { setQuery(""); setCategory("Alle Bereiche"); setStatus("Alle Prüfstände"); }}>Filter zurücksetzen</Button>}</Empty> : <div className="results">{filtered.map(v => <a className="video-row" href={`/analysen/${v.id}`} key={v.id}><div><p className="eyebrow">{v.categories.join(" · ") || "Einordnung offen"}</p><h3>{v.title}</h3><p className="muted">{v.summary || "Zusammenfassung wird beim Prüfen ergänzt."}</p><div className="tags">{v.tags.map(t => <span key={t}>{t}</span>)}</div></div><div className="row-meta"><span className="badge">{queue.some(q => q.videoId === v.id) ? "Erneut prüfen" : v.revisions.length ? `Prüfung · v${v.revisions.length}` : "Noch ungeprüft"}</span><p className="small muted">{new Date(v.importedAt).toLocaleDateString("de-DE")}</p></div></a>)}</div>}
 </section><footer>Business-Ideen / Sidehustles · Sportwetten · KDP-Buchbusiness · KI & Automation</footer></main>;
}
