"use client";
import taxonomy from "@/lib/taxonomy.json";
import { tagSlug } from "@/lib/tags";
import { useState } from "react";
import type { Video } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from "@/components/ui/empty";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
const categories = ["Business-Ideen / Sidehustles", "Sportwetten", "KDP-Buchbusiness", "KI & Automation"];
export default function Dashboard({ videos, queue }: { videos: Video[]; queue: { videoId: string; reason: string }[] }) {
 const [query, setQuery] = useState(""); const [category, setCategory] = useState("Alle Bereiche"); const [status, setStatus] = useState("Alle Prüfstände");
 const [section, setSection] = useState("Alle Untersektionen");
 const chooseCategory = (value: string) => { setCategory(value); setSection("Alle Untersektionen"); };
 const availableSections = taxonomy[category as keyof typeof taxonomy] ?? [];
 const filtered = videos.filter(v => (category === "Alle Bereiche" || v.categories.includes(category)) && (section === "Alle Untersektionen" || v.sections.some(s => s.category === category && s.section === section)) && (status === "Alle Prüfstände" || (status === "Noch ungeprüft" ? !v.revisions.length : status === "Erneut prüfen" ? queue.some(q => q.videoId === v.id) : !!v.revisions.length)) && [v.title, v.summary, v.channel, ...v.tags].join(" ").toLocaleLowerCase("de").includes(query.toLocaleLowerCase("de")));
 return <main className="workspace"><header className="masthead"><a href="/" className="brand">MC<span>WISSENSPLATTFORM</span></a><form action="/api/logout" method="post"><Button variant="outline" type="submit">Abmelden</Button></form></header>
 <section className="heading"><div><p className="eyebrow">DEIN RECHERCHEARCHIV</p><h1>Wissen, das einer<br className="desktop-break"/> Prüfung standhält.</h1></div><p className="heading-note">Ideen entdecken. Belege hinterfragen.<br/>Erkenntnisse mit jedem Video weiterentwickeln.</p></section>
 <section className="metrics" aria-label="Übersicht"><div><strong>{videos.length}</strong><span>Analysen</span></div><div><strong>{videos.filter(v => v.revisions.length).length}</strong><span>Mit Gegenprüfung</span></div><div><strong>{queue.length}</strong><span>Erneut zu prüfen</span></div></section>
 <nav className="category-grid" aria-label="Kategorien"><Button variant={category === "Alle Bereiche" ? "default" : "outline"} onClick={() => {chooseCategory("Alle Bereiche");setQuery("");setStatus("Alle Prüfstände");}} data-category="Alle Bereiche">Alle Analysen ({videos.length})</Button>{categories.map(c => <Button key={c} variant={category === c ? "default" : "outline"} data-category={c} onClick={() => {chooseCategory(c);setQuery("");setStatus("Alle Prüfstände");}}>{c} ({videos.filter(v => v.categories.includes(c)).length})</Button>)}</nav>
 <section className="subsection-panel" hidden={category === "Alle Bereiche"} aria-label="Untersektionen"><p className="eyebrow">Untersektionen · {category}</p><nav className="subsection-grid" aria-label="Untersektion wählen">{["Alle Untersektionen", ...availableSections].map(s => <button key={s} type="button" data-section={s} aria-pressed={section === s} onClick={() => setSection(s)}>{s} ({videos.filter(v => v.categories.includes(category) && (s === "Alle Untersektionen" || v.sections.some(a => a.category === category && a.section === s))).length})</button>)}</nav></section>
 <section className="library"><div className="section-heading"><h2>{category === "Alle Bereiche" ? "Letzte Analysen" : category + (section === "Alle Untersektionen" ? "" : " · " + section)}</h2><a href="/methodik">So bewerten wir</a></div>
 <div className="controls"><label className="search"><span className="sr-only">Analysen durchsuchen</span><Input placeholder="Titel, Thema oder Tool suchen …" value={query} onChange={e => setQuery(e.target.value)}/></label><Select value={category} onValueChange={chooseCategory}><SelectTrigger aria-label="Themenbereich"><SelectValue/></SelectTrigger><SelectContent>{["Alle Bereiche", ...categories].map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger aria-label="Prüfstand"><SelectValue/></SelectTrigger><SelectContent>{["Alle Prüfstände", "Noch ungeprüft", "Mit Gegenprüfung", "Erneut prüfen"].map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div>
 <button type="button" data-reset-filters onClick={() => {chooseCategory("Alle Bereiche");setStatus("Alle Prüfstände");setQuery("");}}>Alle anzeigen / Filter zurücksetzen</button><p className="small muted" role="status">{filtered.length} {filtered.length === 1 ? "Analyse" : "Analysen"}</p>
 {!filtered.length ? <Empty className="empty-state"><EmptyHeader><EmptyTitle>{videos.length ? "Keine passenden Analysen" : "Platz für deine erste Analyse"}</EmptyTitle><EmptyDescription>{videos.length ? "Ändere den Suchbegriff oder die Filter." : "Lade deine erste HTML-Datei im gemeinsamen Codex-Task hoch. Nach dem Import findest du hier die Analyse, ihre Einordnung und unsere Gegenprüfung."}</EmptyDescription></EmptyHeader>{videos.length > 0 && <Button variant="outline" onClick={() => { setQuery(""); chooseCategory("Alle Bereiche"); setStatus("Alle Prüfstände"); }}>Filter zurücksetzen</Button>}</Empty> : <div className="results">{filtered.map(v => <article className="video-row" data-video-id={v.id} key={v.id}><div><p className="eyebrow">{v.categories.join(" · ") || "Einordnung offen"}</p><p className="small muted">{v.sections.filter(s => category === "Alle Bereiche" || s.category === category).map(s => s.section).filter((s, i, a) => a.indexOf(s) === i).join(" · ")}</p><h3><a href={`/analysen/${v.id}`}>{v.title}</a></h3><p className="muted">{v.summary || "Zusammenfassung wird beim Prüfen ergänzt."}</p><div className="tags">{v.tags.map(t => <a key={t} href={`/tags/${tagSlug(t)}`}>{t}</a>)}</div></div><div className="row-meta"><span className="badge">{queue.some(q => q.videoId === v.id) ? "Erneut prüfen" : v.revisions.length ? `Prüfung · v${v.revisions.length}` : "Noch ungeprüft"}</span><p className="small muted">{new Date(v.importedAt).toLocaleDateString("de-DE")}</p></div></article>)}</div>}
 </section><footer>Business-Ideen / Sidehustles · Sportwetten · KDP-Buchbusiness · KI & Automation</footer></main>;
}
